### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by zerobasa** [ClassicBrawlTeam/BrawlStars-v31#3]
Traceback (most recent call last):
  File "C:\Users\User\Desktop\BrawlStars-v31-main\Main.py", line 19, in <module>
    main()
  File "C:\Users\User\Desktop\BrawlStars-v31-main\Main.py", line 15, in main
    Server("192.168.0.136", 9339).start()
  File "C:\Users\User\Desktop\BrawlStars-v31-main\Core\Networking\Server.py", line 18, in __init__
    self.db = MongoDB(self.config['MongoConnectionURL'])
  File "C:\Users\User\Desktop\BrawlStars-v31-main\DataBase\MongoDB.py", line 15, in __init__
    self.client = pymongo.MongoClient(conn_str)
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\pymongo\mongo_client.py", line 680, in __init__
    seeds.update(uri_parser.split_hosts(entity, port))
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\pymongo\uri_parser.py", line 359, in split_hosts
    raise ConfigurationError("Empty host "
pymongo.errors.ConfigurationError: Empty host (or extra comma in host list).

**Comment by ShockWave5158** [comment]
This is not a bug. Before running the server you are required to add your MongoDB URL in config.json
